console.log("Hello world");
let today = new Date;
// console.log(typeof today);
let otherdate = new Date('8-4-2003 4:54:08');
console.log(otherdate);
let a;
a = otherdate.getDay();
a = otherdate.getTime();
a = otherdate.getMinutes();
console.log(a);